import {
  FileDown,
  FileText,
  Merge,
  Scissors,
  Image,
  FileUp,
  PenTool,
  RotateCw,
  Table2,
  Lock,
  Presentation,
  Globe,
} from 'lucide-react';

export const tools = [
  {
    id: 'pdf-to-word',
    path: '/pdf-to-word',
    icon: FileText,
    nameKey: 'pdfToWord',
    descKey: 'pdfToWordDesc',
    headlineKey: 'pdfToWordHeadline',
    accept: '.pdf',
    color: 'blue',
  },
  {
    id: 'compress-pdf',
    path: '/compress-pdf',
    icon: FileDown,
    nameKey: 'compressPdf',
    descKey: 'compressPdfDesc',
    headlineKey: 'compressPdfHeadline',
    accept: '.pdf',
    color: 'emerald',
  },
  {
    id: 'merge-pdf',
    path: '/merge-pdf',
    icon: Merge,
    nameKey: 'mergePdf',
    descKey: 'mergePdfDesc',
    headlineKey: 'mergePdfHeadline',
    accept: '.pdf',
    multiple: true,
    color: 'violet',
  },
  {
    id: 'pdf-to-jpg',
    path: '/pdf-to-jpg',
    icon: Image,
    nameKey: 'pdfToJpg',
    descKey: 'pdfToJpgDesc',
    headlineKey: 'pdfToJpgHeadline',
    accept: '.pdf',
    color: 'pink',
  },
  {
    id: 'split-pdf',
    path: '/split-pdf',
    icon: Scissors,
    nameKey: 'splitPdf',
    descKey: 'splitPdfDesc',
    headlineKey: 'splitPdfHeadline',
    accept: '.pdf',
    color: 'orange',
  },
  {
    id: 'pdf-to-excel',
    path: '/pdf-to-excel',
    icon: Table2,
    nameKey: 'pdfToExcel',
    descKey: 'pdfToExcelDesc',
    headlineKey: 'pdfToExcelHeadline',
    accept: '.pdf',
    color: 'green',
  },
  {
    id: 'word-to-pdf',
    path: '/word-to-pdf',
    icon: FileUp,
    nameKey: 'wordToPdf',
    descKey: 'wordToPdfDesc',
    headlineKey: 'wordToPdfHeadline',
    accept: '.docx,.doc,.pptx,.xlsx',
    color: 'sky',
  },
  {
    id: 'pdf-to-powerpoint',
    path: '/pdf-to-powerpoint',
    icon: Presentation,
    nameKey: 'pdfToPowerpoint',
    descKey: 'pdfToPowerpointDesc',
    headlineKey: 'pdfToPowerpointHeadline',
    accept: '.pdf',
    color: 'orange',
  },
  {
    id: 'protect-pdf',
    path: '/protect-pdf',
    icon: Lock,
    nameKey: 'protectPdf',
    descKey: 'protectPdfDesc',
    headlineKey: 'protectPdfHeadline',
    accept: '.pdf',
    color: 'red',
  },
  {
    id: 'sign-pdf',
    path: '/sign-pdf',
    icon: PenTool,
    nameKey: 'signPdf',
    descKey: 'signPdfDesc',
    headlineKey: 'signPdfHeadline',
    accept: '.pdf',
    color: 'amber',
  },
  {
    id: 'organize-pdf',
    path: '/organize-pdf',
    icon: RotateCw,
    nameKey: 'organizePdf',
    descKey: 'organizePdfDesc',
    headlineKey: 'organizePdfHeadline',
    accept: '.pdf',
    color: 'teal',
  },
  {
    id: 'web-to-pdf',
    path: '/web-to-pdf',
    icon: Globe,
    nameKey: 'webToPdf',
    descKey: 'webToPdfDesc',
    headlineKey: 'webToPdfHeadline',
    color: 'cyan',
  },
];